name: "Build In Pull Request"

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-all-dev

      - name: Configure CMake
        run: cmake -B build -DPATCH_VERSION=${{ github.run_number }}

      - name: Build Project
        run: cmake --build build

      - name: Run Tests
        run: cmake --build build --target test

      - name: Comment on PR if build fails
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const pr_number = context.issue.number;
            const run_url = `https://github.com/${owner}/${repo}/actions/runs/${context.runId}`;
            
            const body = `❌ **Build Failed!**\n\nPlease check the workflow logs for details: [View Run](${run_url})`;
            
            await github.rest.issues.createComment({
              owner: owner,
              repo: repo,
              issue_number: pr_number,
              body: body
            });